development:
  url: https://localhost:4000

staging:
  url: https://dev.masilotti.com

production:
  url: https://masilotti.com

permalink: pretty
template_engine: erb

# TODO: Categories, tags, or custom taxonomies for turbo-ios series.
# https://www.bridgetownrb.com/docs/resources#taxonomies
