development:
  url: https://localhost:4000

staging:
  url: https://dev.masilotti.com

production:
  url: https://masilotti.com

# TODO: Move to config/initializers.rb.
collections:
  hotwire:
    output: true
  snippets:
    output: false

# TODO: Categories, tags, or custom taxonomies for turbo-ios series.
# https://www.bridgetownrb.com/docs/resources#taxonomies
